# Generated by Django 4.2.7 on 2023-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100, null=True)),
                ('licience', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('shift', models.IntegerField()),
                ('isactive', models.IntegerField()),
                ('createdby', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100, null=True)),
                ('licience', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('shift', models.IntegerField()),
                ('drivertype', models.IntegerField()),
                ('isactive', models.IntegerField()),
                ('createdby', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='supervisor',
            name='aadhar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
