# Generated by Django 4.2.7 on 2023-11-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_cleaners_drivers_supervisor_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='drivertype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='shift',
            field=models.CharField(max_length=100),
        ),
    ]
