# Generated by Django 4.2.7 on 2023-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_drivers_drivertype_alter_drivers_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaners',
            name='shift',
            field=models.CharField(max_length=100),
        ),
    ]
